### ISSUE TITLE
question: use a keymapping that accepts AI input

### ISSUE THREAD

**Issue by azinsharaf** [aduros/ai.vim#7]
how can i create a key mapping that asks for an input? For instance I have added this:

`map("n", "<Leader>a", ":AI<CR>")`
but the command should be `:AI <type a question here>`
I want to have the AI plugin input mode when I press `<leader>A`

**Comment by aduros** [comment]
Hi, I think you just need to replace the `<CR>` with a space in your mapping. Eg: `map("n", "<Leader>a", ":AI ")`

**Comment by azinsharaf** [comment]
yes, it worked. Thanks!
